# Site settings
title: João Paulo M. Oliveira
email: joaopaulo_oli@hotmail.com
url:
baseurl: ""
description:
keywords: 
skills: "Game Developer | Unity Software Engineer | C#"
meta_author: "Oliveira João"
title_social: Social Media

# Google webmaster tools
google_verify: 

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Jottap

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 35ad31
  primary-rgb: "0, 0, 0" 
  secondary: 353535 
  secondary-dark: 353535 

# Colors
#  - gray : 353535
#  - gray light : 666666
#  - green : 35ad31

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: 
  - title: github
    url: https://github.com/jottap
  - title: linkedin-in
    url: https://www.linkedin.com/in/joao-paulo-oli/
  - title: itch-io
    url: https://jottap.itch.io/

# Postal address (add as many lines as necessary)
address:
  - line: 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

curriculum: JoaoPaulo_Unity_Developer.pdf

about: "<p> Graduated in computer science with extensive knowledge in Unity, C# and object-oriented programming.
Proficient in Clean Code and Clean Architecture. <p>I began my professional career as a Systems Programmer, gaining knowledge and practices connected to
the area of my fascination: game development, due to my passion for the RPG genre. <p>Extensive IT knowledge with a primary focus on working as a Unity Developer. My main projects include
multiplayer, card, casual, minigames, and educational games. Apps development for platforms of
mini-games and interactive books. Also created projects for web, PC, and mobile devices (Android and
iOS).</p>"