# Site settings
title: João Paulo M. Oliveira
email: joaopaulo_oli@hotmail.com
url:
baseurl: ""
description:
keywords: 
skills: "Game Developer | Unity Software Engineer | C#"
meta_author: "Oliveira João"
title_social: Social Media

# Google webmaster tools
google_verify: 

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Jottap

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 35ad31
  primary-rgb: "0, 0, 0" #"24,288,156" #"128,179,255"
  secondary: 353535 #FFCC00 #2c3e50 #FD6E8A
  secondary-dark: 000000 #e0c600 #233140 #A2122F

#cores
# cinza : 353535
# cinza claro : 666666
# amarelo : 
# green : 35ad31

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: 
  - title: github
    url: https://github.com/jottap
  - title: linkedin
    url: https://www.linkedin.com/in/joao-paulo-oli/

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

about: "Graduated in Computer Science in 2015 with
experiences
● Unity 3D engine
● C#
● Database "